name: End-to-end tests
on:
  push:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          node-version: ${{matrix.node-version}}
          build: npm run build:production
          start: npm start
          wait-on: http://localhost:4200
