name: End-to-end tests
on:
  push:
    branches:
      - staging
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
        machines: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        continue-on-error: false
        uses: cypress-io/github-action@v2
        with:
          node-version: ${{matrix.node-version}}
          build: npm run build:testing
          start: npm start
          wait-on: http://localhost:4200

      - name: Merge staging -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
